export const DUMMY_LISTINGS = [
    {
        id: 1,
        title: "Spacious Room near State St",
        price: 850,
        bedrooms: 2,
        location: "Downtown Madison",
        amenities: ["In-unit Laundry", "Furnished", "Gym"],
        description: "Looking for a roommate! The apartment is fully furnished and incredibly close to State Street dining options and campus. You'll have your own bathroom and access to the building's gym.",
        images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80", "https://images.unsplash.com/photo-1502672260266-1c1de2d93688?auto=format&fit=crop&w=800&q=80"],
        startDate: "2026-05-15",
        endDate: "2026-08-15",
        contactEmail: "roommate1@wisc.edu",
        roommatePrefs: { petFriendly: true, smokingAllowed: false, studyFriendly: true }
    },
    {
        id: 2,
        title: "Camp Randall Sublet",
        price: 600,
        bedrooms: 4,
        location: "Campus Area",
        amenities: ["Parking", "A/C"],
        description: "Fantastic spot right next to Camp Randall for incredible game day experiences! Looking to sublet one bedroom in a 4-bedroom house. Great roommates, quiet block.",
        images: ["https://images.unsplash.com/photo-1502672260266-1c1de2d93688?auto=format&fit=crop&w=800&q=80"],
        startDate: "2026-09-01",
        endDate: "2027-05-31",
        contactEmail: "sportsfan@wisc.edu",
        roommatePrefs: { petFriendly: false, smokingAllowed: true, studyFriendly: false }
    },
    {
        id: 3,
        title: "Luxury 1 Bed Apartment",
        price: 1200,
        bedrooms: 1,
        location: "Capitol Square",
        amenities: ["Pool", "Gym", "Doorman", "Pet Friendly"],
        description: "Experience premium living right on Capitol Square. This beautiful 1 bedroom includes all building amenities such as a rooftop pool and full fitness center. Perfect for a senior or grad student.",
        images: ["https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=800&q=80", "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80", "https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&w=800&q=80"],
        startDate: "2026-08-15",
        endDate: "2027-08-14",
        contactEmail: "capitolliv@gmail.com",
        roommatePrefs: { petFriendly: true, smokingAllowed: false, studyFriendly: true }
    },
    {
        id: 4,
        title: "Cozy Studio Walkable to Class",
        price: 950,
        bedrooms: 1,
        location: "Langdon/State Street",
        amenities: ["Furnished", "Utilities Included"],
        description: "A very cozy studio located steps away from Memorial Union and classes on Langdon. Furniture and utilities are fully included in the rent price for an easy move-in.",
        images: ["https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=800&q=80"],
        startDate: "2026-06-01",
        endDate: "2026-12-31",
        contactEmail: "langdonstudio@wisc.edu",
        roommatePrefs: { petFriendly: false, smokingAllowed: false, studyFriendly: true }
    },
    {
        id: 5,
        title: "Huge 3 Bedroom Sublease",
        price: 2100,
        bedrooms: 3,
        location: "Monroe Street",
        amenities: ["Backyard", "Garage", "Washer/Dryer"],
        description: "Massive 3 bedroom house available for the spring semester! Features a beautiful private backyard, two-car garage, and recently updated appliances. Close to Trader Joe's.",
        images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80"],
        startDate: "2027-01-01",
        endDate: "2027-05-30",
        contactEmail: "monroehouse@gmail.com",
        roommatePrefs: { petFriendly: true, smokingAllowed: false, studyFriendly: false }
    },
    {
        id: 6,
        title: "Affordable Shared Room",
        price: 450,
        bedrooms: 2,
        location: "Regent Neighborhood",
        amenities: ["Balcony", "A/C", "Dishwasher"],
        description: "Very budget-friendly shared room in the Regent neighborhood. The apartment has a nice balcony with a great view and a modern kitchen with a dishwasher.",
        images: ["https://images.unsplash.com/photo-1598928506311-c55dd5802a43?auto=format&fit=crop&w=800&q=80"],
        startDate: "2026-05-15",
        endDate: "2026-08-15",
        contactEmail: "regent.roommate@wisc.edu",
        roommatePrefs: { petFriendly: false, smokingAllowed: false, studyFriendly: true }
    },
    {
        id: 7,
        title: "Modern 4B/2B Townhouse",
        price: 3200,
        bedrooms: 4,
        location: "Vilas Area",
        amenities: ["In-unit Laundry", "Basement", "Parking"],
        description: "Brand new modern townhouse perfect for a group of 4. Includes a large finished basement for entertainment, multiple parking spots, and beautiful finishes throughout.",
        images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80"],
        startDate: "2026-08-01",
        endDate: "2027-07-31",
        contactEmail: "vilas4bed@gmail.com",
        roommatePrefs: { petFriendly: true, smokingAllowed: true, studyFriendly: false }
    },
    {
        id: 8,
        title: "Sunny 1 Bedroom close to UW",
        price: 1100,
        bedrooms: 1,
        location: "University Ave",
        amenities: ["Gym", "Secure Entry", "Furnished"],
        description: "Incredible natural light in this 1 bedroom right on University Ave. Highly secure building with electronic locks and a modern fitness center on the first floor.",
        images: ["https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&w=800&q=80"],
        startDate: "2026-06-01",
        endDate: "2026-08-15",
        contactEmail: "univ.apts@gmail.com",
        roommatePrefs: { petFriendly: true, smokingAllowed: false, studyFriendly: true }
    }
];
